---
brew:
  tap:
    - caskroom/cask
  brew:
    - awscli
    - bash-completion
    - bork
    - coreutils
    - curl
    - git
    - jq
    - mackup
    - openssh
    - vim
    - wget
  cask:
    - 1password
    - adobe-creative-cloud
    - aerial
    - atom
    - beamer
    - daisydisk
    - docker
    - dropbox
    - firefox
    - flux
    - google-chrome
    - google-drive-file-stream
    - handbrake
    - istat-menus
    - iterm2
    - kaleidoscope
    - keybase
    - muzzle
    - private-internet-access
    - sketch
    - slack
    - spectacle
    - spotify
    - steam
    - the-unarchiver
    - tower
    - vlc
  mas:
    - { name: Final Cut Pro, id: 424389933 }
    - { name: iMovie, id: 408981434 }
    - { name: Magnet, id: 441258766 }

mackup:
  storage:
    engine: dropbox
  applications_to_sync:
    - 1password-4
    - atom
    - aws
    - bash
    - daisydisk
    - docker
    - flux
    - git
    - istat-menus-5
    - iterm2
    - kaleidoscope
    - sketch
    - spotify
    - ssh
    - tower-2
    - vlc

misc:
  # System
  font:
    name: SourceCodePro-Regular.otf
    download: https://github.com/adobe-fonts/source-code-pro/archive/release.zip
    path: source-code-pro-release/OTF
  screensaver:
    name:
      defaults:
        ~/Library/Preferences/ByHost/com.apple.screensaver.UUID.plist:
          # Arrange by
          - { key: "moduleDict:displayName", type: string, value: Aerial }
          - { key: "moduleDict:moduleName", type: string, value: Aerial }
          - { key: "moduleDict:path", type: string, value: "~/Library/Screen Savers/Aerial.saver" }
    idle_time:
      defaults:
        ~/Library/Preferences/ByHost/com.apple.screensaver.UUID.plist:
          # Start after (dropdown)
          - { key: idleTime, type: integer, value: 120 }
  # Apps
  chrome:
    set_as_default: true
    defaults:
      com.google.Chrome:
        # Disable the all too sensitive backswipe on trackpads and Magic Mouse
        - { key: AppleEnableSwipeNavigateWithScrolls, type: bool, value: false }
        - { key: AppleEnableMouseSwipeNavigateWithScrolls, type: bool, value: false }
  iterm2:
    import_style: true
    shell_integration: true
    defaults:
      com.googlecode.iterm2:
        # Don’t display the annoying prompt when quitting iTerm
        - { key: PromptOnQuit, type: bool, value: false }
        # Don’t display the annoying update prompt
        - { key: SUEnableAutomaticChecks, type: bool, value: false }

system:
  defaults:
    NSGlobalDomain:
      # System Preferences > General
      # Appearance (dropdown)
      - { key: AppleAquaColorVariant, type: int, value: 6 }
      # Use dark menu bar and Dock (checkbox)
      - { key: AppleInterfaceStyle, type: string, value: Dark }

      # System Preferences > Acessibility
      # Display > Shake mouse pointer to locate (checkbox)
      - { key: CGDisableCursorLocationMagnification, type: bool, value: true }

      # System Preferences > Keyboard
      # Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
      - { key: AppleKeyboardUIMode, type: int, value: 3 }
      # Disable smart quotes and dashes (hidden)
      - { key: NSAutomaticQuoteSubstitutionEnabled, type: bool, value: false }
      - { key: NSAutomaticDashSubstitutionEnabled, type: bool, value: false }
      # Disable auto-correct (hidden)
      - { key: NSAutomaticSpellingCorrectionEnabled, type: bool, value: false }
      # Disable press-and-hold for keys in favor of key repeat (hidden)
      - { key: ApplePressAndHoldEnabled, type: bool, value: false }
      # Set a blazingly fast keyboard repeat rate (hidden)
      - { key: KeyRepeat, type: int, value: 2 }

      # System Preferences > Mouse
      # Scroll direction: natural (checkbox)
      - { key: com.apple.swipescrolldirection, type: bool, value: false }

      # Other hidden preferences
      # Speed up window resize animations
      - { key: NSWindowResizeTime, type: float, value: 0.001 }
      # Expand save panel by default
      - { key: NSNavPanelExpandedStateForSaveMode, type: bool, value: true }
      - { key: NSNavPanelExpandedStateForSaveMode2, type: bool, value: true }
      # Expand print panel by default
      - { key: PMPrintingExpandedStateForPrint, type: bool, value: true }
      - { key: PMPrintingExpandedStateForPrint2, type: bool, value: true }
      # Save to disk (not to iCloud) by default
      - { key: NSDocumentSaveNewDocumentsToCloud, type: bool, value: false }

    # System Preferences > Dock
    com.apple.dock:
      # Size (slider)
      - { key: tilesize, type: float, value: 43 }
      # Magnification (slider)
      - { key: largesize, type: int, value: 48 }
      # Magnification (checkbox)
      - { key: magnification, type: bool, value: true }
      # Automatically hide and show the Dock (checkbox)
      - { key: autohide, type: bool, value: true }
      # Delay (hidden)
      - { key: autohide-delay, type: int, value: 0 }
      # Semi transparent dock icons for hidden apps (hidden)
      - { key: showhidden, type: bool, value: true }

    # System Preferences > Security & Privacy
    com.apple.screensaver:
      # Require password (checkbox)
      - { key: askForPassword, type: int, value: 1 }
      # Require password (dropdown)
      - { key: askForPasswordDelay, type: float, value: 60 }

    # System Preferences > Mouse
    com.apple.driver.AppleBluetoothMultitouch.mouse:
      # Secondary click (checkbox)
      - { key: MouseButtonMode, type: string, value: TwoButton }

    # System Preferences > Trackpad
    com.apple.driver.AppleBluetoothMultitouch.trackpad:
      # Tap to click (checkbox)
      - { key: Clicking, type: int, value: 1 }

    # System Preferences > Printers & Scanners
    com.apple.print.PrintingPrefs:
      # Automatically quit printer app once the print jobs complete (hidden)
      - { key: Quit When Finished, type: bool, value: true }

    # System Preferences > Sharing
    com.apple.NetworkBrowser:
      # Enable AirDrop over ethernet
      - { key: BrowseAllInterfaces, type: bool, value: true }

    # System Preferences > Time Machine
    com.apple.TimeMachine:
      # Prevent Time Machine from prompting to use new hard drives as backup volume
      - { key: DoNotOfferNewDisksForBackup, type: bool, value: true }

    # Other hidden preferences
    com.apple.frameworks.diskimages:
      # Disable disk image verification
      - { key: skip-verify, type: bool, value: true }
      - { key: skip-verify-locked, type: bool, value: true }
      - { key: skip-verify-remote, type: bool, value: true }

    com.apple.LaunchServices:
      # Disable the "Are you sure you want to open this application?"x dialog
      - { key: LSQuarantine, type: bool, value: false }

    # Finder
    com.apple.finder:
      # Show hidden files
      - { key: AppleShowAllFiles, type: string, value: YES }
      # Show status bar
      - { key: NewWindowTarget, type: string, value: PfHm }
      # Show status bar
      - { key: ShowStatusBar, type: bool, value: true }
      # Disable the warning when changing a file extension
      - { key: FXEnableExtensionChangeWarning, type: bool, value: false }
      # When performing a search, search the current folder by default
      - { key: FXDefaultSearchScope, type: string, value: SCcf }
      # Use column view in all Finder windows by default
      - { key: FXPreferredViewStyle, type: string, value: clmv }
      # Show status bar
      - { key: FXPreferredGroupBy, type: string, value: Kind }
      # Allow text selection in Quick Look
      - { key: QLEnableTextSelection, type: bool, value: true }
      # Show icons for hard drives, servers, and removable media on the desktop
      - { key: ShowExternalHardDrivesOnDesktop, type: bool, value: true }
      - { key: ShowHardDrivesOnDesktop, type: bool, value: true }
      - { key: ShowMountedServersOnDesktop, type: bool, value: true }
      - { key: ShowRemovableMediaOnDesktop, type: bool, value: true }

    com.apple.desktopservices:
      # Avoid creating .DS_Store files on network volumes
      - { key: DSDontWriteNetworkStores, type: bool, value: true }

  defaults_global:
    # Displays
    /Library/Preferences/com.apple.iokit.AmbientLightSensor:
      # Automatically adjust brightness
      - { key: "Automatic Display Enabled", type: bool, value: false }

  # Need manual commands for arrays, as they aren't well supported in bork or plistbuddy
  defaults_arrays:
    # System Preferences > Dock
    com.apple.dock:
      # Remove all apps (hidden)
      - { key: persistent-apps, type: array, value: "" }
      # Add new apps (hidden)
      - { key: persistent-apps, type: array-add, value: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Google Chrome.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" }
      - { key: persistent-apps, type: array-add, value: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Spotify.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" }
      - { key: persistent-apps, type: array-add, value: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Slack.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" }
      - { key: persistent-apps, type: array-add, value: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Atom.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" }
      - { key: persistent-apps, type: array-add, value: "<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/iTerm.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>" }

    # Menu bar
    com.apple.systemuiserver:
      # Remove apps
      - { key: menuExtras, type: array, value: "" }
      # Add apps
      - { key: menuExtras, type: array-add, value: "/System/Library/CoreServices/Menu Extras/Battery.menu" }
      - { key: menuExtras, type: array-add, value: "/System/Library/CoreServices/Menu Extras/Bluetooth.menu" }
      - { key: menuExtras, type: array-add, value: "/System/Library/CoreServices/Menu Extras/AirPort.menu" }
      - { key: menuExtras, type: array-add, value: "/System/Library/CoreServices/Menu Extras/Volume.menu" }

  defaults_plistbuddy:
    # System Preferences > Keyboard > Shortcuts > Spotlight
    ~/Library/Preferences/com.apple.symbolichotkeys.plist:
      # Uncheck `Show Finder search window`
      - { key: "AppleSymbolicHotKeys:65:enabled", type: bool, value: false }

    # Finder
    ~/Library/Preferences/com.apple.finder.plist:
      # Arrange by
      - { key: "DesktopViewSettings:IconViewSettings:arrangeBy", type: string, value: grid }
      - { key: "FK_StandardViewSettings:IconViewSettings:arrangeBy", type: string, value: grid }
      - { key: "StandardViewSettings:IconViewSettings:arrangeBy", type: string, value: grid }
      # Grid spacing
      - { key: "DesktopViewSettings:IconViewSettings:gridSpacing", type: integer, value: 40 }
      - { key: "FK_StandardViewSettings:IconViewSettings:gridSpacing", type: integer, value: 40 }
      - { key: "StandardViewSettings:IconViewSettings:gridSpacing", type: integer, value: 40 }
      # Icon size
      - { key: "DesktopViewSettings:IconViewSettings:iconSize", type: integer, value: 44 }
      - { key: "FK_StandardViewSettings:IconViewSettings:iconSize", type: integer, value: 44 }
      - { key: "StandardViewSettings:IconViewSettings:iconSize", type: integer, value: 44 }
      # Label on bottom
      - { key: "DesktopViewSettings:IconViewSettings:labelOnBottom", type: bool, value: false }
      - { key: "FK_StandardViewSettings:IconViewSettings:labelOnBottom", type: bool, value: false }
      - { key: "StandardViewSettings:IconViewSettings:labelOnBottom", type: bool, value: false }
      # Text size
      - { key: "DesktopViewSettings:IconViewSettings:textSize", type: integer, value: 10 }
      - { key: "FK_StandardViewSettings:IconViewSettings:textSize", type: integer, value: 10 }
      - { key: "StandardViewSettings:IconViewSettings:textSize", type: integer, value: 10 }

# # System Preferences > Security & Privacy > General > Allow apps downloaded from: Anywhere
# spctl_status: disable
#
# # System Preferences > Sharing > Computer Name
# computer_names:
#   - { name: ComputerName, value: {{ user_name }}-macbook }
#   - { name: LocalHostName, value: {{ user_name }}-macbook }
#   - { name: HostName, value: {{ user_name }}-macbook.local }
#
# # System Preferences > Energy Saver
# power_settings_all:
#   - { name: disksleep, value: 10 }
#   - { name: womp, value: 0 }
#   - { name: autorestart, value: 0 }
#   - { name: halfdim, value: 0 }
#   - { name: sms, value: 0 }
#
# # System Preferences > Energy Saver > Battery
# power_settings_battery:
#   - { name: displaysleep, value: 5 }
#   - { name: sleep, value: 10 }
#   - { name: powernap, value: 0 }
#   - { name: lessbright, value: 1 }
#
# # System Preferences > Energy Saver > Power Adaptor
# power_settings_charger:
#   - { name: displaysleep, value: 10 }
#   - { name: sleep, value: 0 }
#   - { name: powernap, value: 1 }
#   - { name: lessbright, value: 0 }
