---
# - name: load backup file
#   include_vars: "{{ playbook_dir }}/vars/apps.backup.yml"
#
# # homebrew
# - name: undo homebrew taps
#   homebrew_tap:
#     name: "{{ item }}"
#     state: absent
#   with_items: "{{ homebrew_taps | difference(last_homebrew_taps) }}"
#
# - name: undo homebrew formulae
#   homebrew:
#     name: "{{ item }}"
#     state: absent
#   with_items: "{{ homebrew_formulae | difference(last_homebrew_formulae) }}"
#
# - name: undo homebrew casks
#   homebrew:
#     name: "{{ item }}"
#     state: absent
#   with_items: "{{ homebrew_casks | difference(last_homebrew_casks) }}"
#
# # npm
# - name: undo npm packages
#   npm:
#     global: yes
#     name: "{{ item }}"
#     state: absent
#   with_items: "{{ npm_packages | difference(last_npm_packages) }}"
#
# # rvm
# - name: undo ruby version
#   shell: rbenv global {{ last_ruby_version }}
