---
- name: check latest ruby version
  shell: echo $(rbenv install -l | grep -v - | tail -1)
  register: latest_ruby_version
  changed_when: false

- name: check current ruby version
  shell: echo $(rbenv version | sed 's/ (.*//')
  register: current_ruby_version
  changed_when: false

- name: install latest ruby version
  shell: rbenv install {{ latest_ruby_version.stdout }}
  when: latest_ruby_version.stdout is defined and latest_ruby_version.stdout != current_ruby_version.stdout

- name: set latest ruby version
  shell: rbenv global {{ ruby_version.stdout }}
  when: latest_ruby_version.stdout is defined and latest_ruby_version.stdout != current_ruby_version.stdout

- name: update rubygems
  become: yes
  command: gem update --system
  when: latest_ruby_version.stdout is defined and latest_ruby_version.stdout != current_ruby_version.stdout
