---
# Ensure bin/fresh is immediately accessible
- name: ensure bin/fresh is executable
  file:
    path: "{{ home }}/.fresh/bin/fresh"
    mode: 0755

- name: ensure bin/fresh is accessible
  become: yes
  file:
    src: "{{ home }}/.fresh/bin/fresh"
    dest: /usr/local/bin/fresh
    state: link

# Create facts `detected_shell` and `shellrc_dir`
- name: detect shell
  action: detect_shell
  changed_when: false

# Create fact `hardware_uuid`
- name: get hardware uuid
  action: hardware_uuid
  changed_when: false

# Create facts `user_name`, `user_name_full` and `user_email`
- name: get user info
  action: user_info
  changed_when: false
