---
- name: read OSX defaults (user)
  shell: defaults read "{{ item.0.domain }}" "{{ item.1.key }}"
  with_subelements:
    - "{{ defaults }}"
    - settings
  register: last_osx_defaults_user
  changed_when: false

- name: read OSX defaults (sudo)
  become: yes
  shell: defaults read "{{ item.0.domain }}" "{{ item.1.key }}"
  with_subelements:
    - "{{ defaults_global }}"
    - settings
  register: last_osx_defaults_sudo
  changed_when: false

- name: read OSX defaults (plistbuddy)
  shell: "/usr/libexec/PlistBuddy -c 'Print :{{ item.1.name }} {{ item.1.value }}' {{ item.0.domain }}"
  with_subelements:
    - "{{ defaults_plistbuddy }}"
    - settings
  register: last_osx_defaults_plistbuddy
  changed_when: false

- name: create rollback.yml
  template:
    src: templates/system.j2
    dest: "{{ playbook_dir }}/vars/system.backup.yml"
    backup: yes
