---
- name: check OSX defaults (user)
  shell: defaults read "{{ item.0.domain }}" "{{ item.1.key }}"
  with_subelements:
    - "{{ defaults }}"
    - settings
  register: last_osx_defaults_user
  failed_when: false
  changed_when: false

- name: check OSX defaults (sudo)
  become: yes
  shell: defaults read "{{ item.0.domain }}" "{{ item.1.key }}"
  with_subelements:
    - "{{ defaults_global }}"
    - settings
  register: last_osx_defaults_sudo
  failed_when: false
  changed_when: false

- name: check OSX defaults (plistbuddy)
  shell: "/usr/libexec/PlistBuddy -c 'Print :{{ item.1.name }} {{ item.1.value }}' {{ item.0.domain }}"
  with_subelements:
    - "{{ defaults_plistbuddy }}"
    - settings
  register: last_osx_defaults_plistbuddy
  failed_when: false
  changed_when: false

- name: check spctl status
  shell: "spctl --status"
  register: last_osx_spctl_status
  failed_when: false
  changed_when: false

- name: check computer name
  shell: "scutil --get {{ item.name }}"
  with_items: "{{ computer_names }}"
  register: last_osx_computer_names
  failed_when: false
  changed_when: false

- name: check power settings
  shell: "pmset -g custom"
  register: last_osx_power_settings
  failed_when: false
  changed_when: false

- name: create rollback.yml
  template:
    src: system.j2
    dest: "{{ playbook_dir }}/vars/system.backup.yml"
    backup: yes
