---
# Create facts `detected_shell` and `shellrc_dir`
- name: detect shell
  action: detect_shell
  changed_when: false

# Create fact `hardware_uuid`
- name: get hardware uuid
  action: hardware_uuid
  changed_when: false

# Create facts `user_name`, `user_name_full` and `user_email`
- name: get user info
  action: user_info
  changed_when: false
