defaults:
  - domain: "NSGlobalDomain"
    settings:
      # System Preferences > General > Appearance (dropdown)
      - { key: "AppleAquaColorVariant", type: "int", value: "6" } # Default: key absent
      # System Preferences > General > Use dark menu bar and Dock (checkbox)
      - { key: "AppleInterfaceStyle", type: "string", value: "Dark" } # Default: key absent
      # System Preferences > Acessibility > Display > Shake mouse pointer to locate (uncheck)
      - { key: "CGDisableCursorLocationMagnification", type: "bool", value: "true" } # Default: key absent

  # System Preferences > Desktop & Screen Saver
  - domain: "ByHost/com.apple.screensaver.{{ uuid }}"
    settings:
      # Start after (dropdown)
      - { key: "idleTime", type: "int", value: "120" } # Default: key absent

  # System Preferences > Dock
  - domain: "com.apple.dock"
    settings:
      # Size (slider)
      - { key: "tilesize", type: "float", value: "43" } # Default: key absent
      # Magnification (slider)
      - { key: "largesize", type: "int", value: "48" } # Default: key absent
      # Magnification (checkbox)
      - { key: "magnification", type: "bool", value: "true" } # Default: key absent
      # Automatically hide and show the Dock (checkbox)
      - { key: "autohide", type: "bool", value: "true" } # Default: key absent
      # Delay (hidden)
      - { key: "autohide-delay", type: "int", value: "0" } # Default: key absent
      # Semi transparent dock icons for hidden apps (hidden)
      - { key: "showhidden", type: "bool", value: "true" } # Default: key absent

      # Array interaction is currently broken :(
      # See: https://github.com/ansible/ansible-modules-extras/issues/2610
      # # Remove all apps (hidden)
      # - { key: "persistent-apps", type: "array", value: "[]" } # Default: [epic array]
      # # Add new apps (hidden)
      # - { key: "persistent-apps", type: "array", array_add: "true", value: "['<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Google Chrome.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>']" }
      # - { key: "persistent-apps", type: "array", array_add: "true", value: "['<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Spotify.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>']" }
      # - { key: "persistent-apps", type: "array", array_add: "true", value: "['<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Slack.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>']" }
      # - { key: "persistent-apps", type: "array", array_add: "true", value: "['<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/Atom.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>']" }
      # - { key: "persistent-apps", type: "array", array_add: "true", value: "['<dict><key>tile-data</key><dict><key>file-data</key><dict><key>_CFURLString</key><string>/Applications/iTerm.app</string><key>_CFURLStringType</key><integer>0</integer></dict></dict></dict>']" }

  # System Preferences > Security & Privacy
  - domain: "com.apple.screensaver"
    settings:
      # Require password (checkbox)
      - { key: "askForPassword", type: "int", value: "1" } # Default: `1`
      # Require password (dropdown)
      - { key: "askForPasswordDelay", type: "float", value: "60" } # Default: `300`

  # System Preferences > Keyboard
  - domain: "NSGlobalDomain"
    settings:
    # Enable full keyboard access for all controls (e.g. enable Tab in modal dialogs)
    - { key: "AppleKeyboardUIMode", type: "int", value: "3" } # Default: key absent
    # Disable smart quotes and dashes (hidden)
    - { key: "NSAutomaticQuoteSubstitutionEnabled", type: "bool", value: "false" } # Default: key absent
    - { key: "NSAutomaticDashSubstitutionEnabled", type: "bool", value: "false" } # Default: key absent
    # Disable auto-correct (hidden)
    - { key: "NSAutomaticSpellingCorrectionEnabled", type: "bool", value: "false" } # Default: key absent
    # Disable press-and-hold for keys in favor of key repeat (hidden)
    - { key: "ApplePressAndHoldEnabled", type: "bool", value: "false" } # Default: key absent
    # Set a blazingly fast keyboard repeat rate (hidden)
    - { key: "KeyRepeat", type: "int", value: "0" } # Default: key absent

  # System Preferences > Mouse
  - domain: "NSGlobalDomain"
    settings:
      # Scroll direction: natural (checkbox)
      - { key: "com.apple.swipescrolldirection", type: "bool", value: "false" } # Default: key absent

  - domain: com.apple.driver.AppleBluetoothMultitouch.mouse
    settings:
      # Secondary click (checkbox)
      - { key: "MouseButtonMode", type: "string", value: "TwoButton" } # Default: `OneButton`

  # System Preferences > Trackpad
  - domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
    settings:
      # Tap to click (checkbox)
      - { key: "Clicking", type: "int", value: "1" } # Default: `0`

  # System Preferences > Printers & Scanners
  - domain: "com.apple.print.PrintingPrefs"
    settings:
      # Automatically quit printer app once the print jobs complete (hidden)
      - { key: "Quit When Finished", type: "bool", value: "true" } # Default: file absent

  # System Preferences > Sharing
  - domain: "com.apple.NetworkBrowser"
    settings:
      # Enable AirDrop over ethernet
      - { key: "BrowseAllInterfaces", type: "bool", value: "true" } # Default: file absent

  # System Preferences > Time Machine
  - domain: "com.apple.TimeMachine"
    settings:
      # Prevent Time Machine from prompting to use new hard drives as backup volume
      - { key: "DoNotOfferNewDisksForBackup", type: "bool", value: "true" } # Default: key absent

  # Other hidden preferences
  - domain: "NSGlobalDomain"
    settings:
      # Speed up window resize animations
      - { key: "NSWindowResizeTime", type: "float", value: "0.001" } # Default: key absent
      # Expand save panel by default
      - { key: "NSNavPanelExpandedStateForSaveMode", type: "bool", value: "true" } # Default: key absent
      - { key: "NSNavPanelExpandedStateForSaveMode2", type: "bool", value: "true" } # Default: key absent
      # Expand print panel by default
      - { key: "PMPrintingExpandedStateForPrint", type: "bool", value: "true" } # Default: key absent
      - { key: "PMPrintingExpandedStateForPrint2", type: "bool", value: "true" } # Default: key absent
      # Save to disk (not to iCloud) by default
      - { key: "NSDocumentSaveNewDocumentsToCloud", type: "bool", value: "false" } # Default: key absent

  - domain: "com.apple.frameworks.diskimages"
    settings:
      # Disable disk image verification
      - { key: "skip-verify", type: "bool", value: "true" } # Default: file absent
      - { key: "skip-verify-locked", type: "bool", value: "true" } # Default: file absent
      - { key: "skip-verify-remote", type: "bool", value: "true" } # Default: file absent

  - domain: "com.apple.LaunchServices"
    settings:
      # Disable the “Are you sure you want to open this application?” dialog
      - { key: "LSQuarantine", type: "bool", value: "false" } # Default: file absent

  # Array interaction is currently broken :(
  # See: https://github.com/ansible/ansible-modules-extras/issues/2610
  # Menu bar
  # - domain: "com.apple.systemuiserver"
  #   settings:
  #     # Remove apps
  #     - { key: "menuExtras", type: "array", value: "[]" } # Default: [epic array]
  #     # Add apps
  #     - { key: "menuExtras", type: "array", array_add: "true", value: "['/System/Library/CoreServices/Menu Extras/Battery.menu']" }
  #     - { key: "menuExtras", type: "array", array_add: "true", value: "['/System/Library/CoreServices/Menu Extras/Bluetooth.menu']" }
  #     - { key: "menuExtras", type: "array", array_add: "true", value: "['/System/Library/CoreServices/Menu Extras/AirPort.menu']" }
  #     - { key: "menuExtras", type: "array", array_add: "true", value: "['/System/Library/CoreServices/Menu Extras/Volume.menu']" }

  # Finder
  - domain: "com.apple.finder"
    settings:
      # Show hidden files
      - { key: "AppleShowAllFiles", type: "bool", value: "true" } # Default: [unknown]
      # Show status bar
      - { key: "NewWindowTarget", type: "string", value: "PfHm" } # Default: key absent
      # Show status bar
      - { key: "ShowStatusBar", type: "bool", value: "true" } # Default: key absent
      # Disable the warning when changing a file extension
      - { key: "FXEnableExtensionChangeWarning", type: "bool", value: "false" } # Default: key absent
      # When performing a search, search the current folder by default
      - { key: "FXDefaultSearchScope", type: "string", value: "SCcf" } # Default: key absent
      # Use column view in all Finder windows by default
      - { key: "FXPreferredViewStyle", type: "string", value: "clmv" } # Default: `Nlsv`
      # Show status bar
      - { key: "FXPreferredGroupBy", type: "string", value: "Kind" } # Default: key absent
      # Allow text selection in Quick Look
      - { key: "QLEnableTextSelection", type: "bool", value: "true" } # Default: key absent
      # Show icons for hard drives, servers, and removable media on the desktop
      - { key: "ShowExternalHardDrivesOnDesktop", type: "bool", value: "true" } # Default: `1`
      - { key: "ShowHardDrivesOnDesktop", type: "bool", value: "true" } # Default: `0``
      - { key: "ShowMountedServersOnDesktop", type: "bool", value: "true" } # Default: key absent
      - { key: "ShowRemovableMediaOnDesktop", type: "bool", value: "true" } # `1``

  - domain: "com.apple.desktopservices"
    settings:
      # Avoid creating .DS_Store files on network volumes
      - { key: "DSDontWriteNetworkStores", type: "bool", value: "true" } # Default: key absent

defaults_global:
  # Displays
  - domain: "/Library/Preferences/com.apple.iokit.AmbientLightSensor"
    settings:
      # Automatically adjust brightness
      - { key: "Automatic Display Enabled", type: "bool", value: "false" } # Default: [unknown]

defaults_plistbuddy:
  # System Preferences > Desktop & Screen Saver
  - domain: "{{ home }}/Library/Preferences/ByHost/com.apple.screensaver.{{ uuid }}.plist"
    settings:
      # Arrange by
      - { key: "moduleDict:displayName", type: "string", value: "Aerial" } # Default: `Computer Name`
      - { key: "moduleDict:moduleName", type: "string", value: "Aerial" } # Default: `Computer Name`
      - { key: "moduleDict:path", type: "string", value: "{{ home }}/Library/Screen Savers/Aerial.saver" } # Default: `/System/Library/Frameworks/ScreenSaver.framework/Resources/Computer Name.saver`

  # System Preferences > Keyboard > Shortcuts > Spotlight
  - domain: "{{ home }}/Library/Preferences/com.apple.symbolichotkeys.plist"
    settings:
      # Uncheck `Show Spotlight search`
      - { key: "AppleSymbolicHotKeys:64:enabled", type: "bool", value: "false" }
      # Uncheck `Show Finder search window`
      - { key: "AppleSymbolicHotKeys:65:enabled", type: "bool", value: "false" }

  # Finder
  - domain: "{{ home }}/Library/Preferences/com.apple.finder.plist"
    settings:
      # Arrange by
      - { key: "DesktopViewSettings:IconViewSettings:arrangeBy", type: "string", value: "grid" } # Default: `none`
      - { key: "FK_StandardViewSettings:IconViewSettings:arrangeBy", type: "string", value: "grid" } # Default: `none`
      - { key: "StandardViewSettings:IconViewSettings:arrangeBy", type: "string", value: "grid" } # Default: `none`
      # Grid spacing
      - { key: "DesktopViewSettings:IconViewSettings:gridSpacing", type: "integer", value: "40" } # Default: `54`
      - { key: "FK_StandardViewSettings:IconViewSettings:gridSpacing", type: "integer", value: "40" } # Default: `54`
      - { key: "StandardViewSettings:IconViewSettings:gridSpacing", type: "integer", value: "40" } # Default: `54`
      # Icon size
      - { key: "DesktopViewSettings:IconViewSettings:iconSize", type: "integer", value: "44" } # Default: `64`
      - { key: "FK_StandardViewSettings:IconViewSettings:iconSize", type: "integer", value: "44" } # Default: `64`
      - { key: "StandardViewSettings:IconViewSettings:iconSize", type: "integer", value: "44" } # Default: `64`
      # Label on bottom
      - { key: "DesktopViewSettings:IconViewSettings:labelOnBottom", type: "bool", value: "false" } # Default: `1`
      - { key: "FK_StandardViewSettings:IconViewSettings:labelOnBottom", type: "bool", value: "false" } # Default: `1`
      - { key: "StandardViewSettings:IconViewSettings:labelOnBottom", type: "bool", value: "false" } # Default: `1`
      # Text size
      - { key: "DesktopViewSettings:IconViewSettings:textSize", type: "integer", value: "10" } # Default: `12`
      - { key: "FK_StandardViewSettings:IconViewSettings:textSize", type: "integer", value: "10" } # Default: `12`
      - { key: "StandardViewSettings:IconViewSettings:textSize", type: "integer", value: "10" } # Default: `12`

# System Preferences > Security & Privacy > General > Allow apps downloaded from: Anywhere
spctl_status: disable

# System Preferences > Sharing > Computer Name
computer_names:
  - { name: "ComputerName", value: "{{ user_name }}-macbook" }
  - { name: "LocalHostName", value: "{{ user_name }}-macbook" }
  - { name: "HostName", value: "{{ user_name }}-macbook" }

# System Preferences > Energy Saver
power_settings_all:
  - { name: "disksleep", value: "10" }
  - { name: "womp", value: "0" }
  - { name: "autorestart", value: "0" }
  - { name: "halfdim", value: "0" }
  - { name: "sms", value: "0" }

# System Preferences > Energy Saver > Battery
power_settings_battery:
  - { name: "displaysleep", value: "5" }
  - { name: "sleep", value: "10" }
  - { name: "powernap", value: "0" }
  - { name: "lessbright", value: "1" }

# System Preferences > Energy Saver > Power Adaptor
power_settings_charger:
  - { name: "displaysleep", value: "10" }
  - { name: "sleep", value: "0" }
  - { name: "powernap", value: "1" }
  - { name: "lessbright", value: "0" }
