---
# homebrew
- name: install homebrew taps
  homebrew_tap:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_taps }}"

- name: install homebrew formulae
  homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_formulae }}"

- name: install homebrew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_casks }}"

# npm
- name: install npm packages
  npm:
    global: yes
    name: "{{ item }}"
  with_items: "{{ npm_packages }}"
