---
- name: list homebrew taps
  shell: brew tap
  register: last_homebrew_taps
  changed_when: false

- name: list homebrew formulae
  shell: brew list
  register: last_homebrew_formulae
  changed_when: false

- name: list homebrew casks
  shell: brew cask list
  register: last_homebrew_casks
  changed_when: false

- name: create rollback.yml
  template:
    src: templates/apps.j2
    dest: "{{ playbook_dir }}/vars/apps.backup.yml"
    backup: yes
