---
- name: list homebrew taps
  shell: brew tap
  register: last_homebrew_taps
  changed_when: false

- name: list homebrew formulae
  shell: brew list
  register: last_homebrew_formulae
  changed_when: false

- name: list homebrew casks
  shell: brew cask list
  register: last_homebrew_casks
  changed_when: false

- name: list npm packages
  shell: ls `npm root -g`
  register: last_npm_packages
  changed_when: false

- name: check current ruby version
  shell: echo $(rbenv version | sed 's/ (.*//')
  register: current_ruby_version
  changed_when: false

- name: create apps.backup.yml
  template:
    src: apps.j2
    dest: "{{ playbook_dir }}/vars/apps.backup.yml"
    backup: yes
