---
- name: disable OS X Gatekeeper
  become: yes
  shell: "spctl --master-disable"
  when: "{{ disable_gatekeeper }}"

- name: set computer name
  shell: "sudo scutil --set {{ item.name }} '{{ item.value }}'"
  with_items: "{{ computer_names }}"

- name: power settings (all)
  shell: "sudo pmset -a {{ item.name }} {{ item.value }}"
  with_items: "{{ power_settings_all }}"

- name: power settings (battery)
  shell: "sudo pmset -a {{ item.name }} {{ item.value }}"
  with_items: "{{ power_settings_battery }}"

- name: power settings (charger)
  shell: "sudo pmset -a {{ item.name }} {{ item.value }}"
  with_items: "{{ power_settings_charger }}"
